[package]
name = "cistron-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cistron = { path = "../../cistron" }
cistron-hgvs = { path = ".." }
cistron-vcf = { path = "../../vcf" }
cistron-liftover = { path = "../../liftover" }

[[bin]]
name = "hgvs_parse"
path = "fuzz_targets/hgvs_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "vcf_parse"
path = "fuzz_targets/vcf_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "chain_parse"
path = "fuzz_targets/chain_parse.rs"
test = false
doc = false
bench = false

[workspace]
