//! HGVS differential: `cistron_hgvs::to_hgvs` (3'-shifted genomic rendering)
//! must match biocommons `hgvs`'s genomic normalizer. The corpus in
//! `hgvs_vectors.tsv` was generated by the reference implementation (see
//! `scripts/gen_hgvs_vectors.py`) over random sequences and variants and
//! committed, so this runs on every `cargo test` with no Python dependency.

use cistron::{Base, Interbase, Variant};
use cistron_hgvs::to_hgvs;

fn bases(s: &str) -> Vec<Base> {
    s.chars()
        .map(|c| match c {
            'A' => Base::A,
            'C' => Base::C,
            'G' => Base::G,
            'T' => Base::T,
            other => panic!("bad base {other}"),
        })
        .collect()
}

#[test]
fn to_hgvs_matches_biocommons() {
    let corpus = include_str!("hgvs_vectors.tsv");
    let (mut agree, mut checked, mut errors) = (0usize, 0usize, 0usize);
    let mut mismatches: Vec<String> = Vec::new();

    for line in corpus.lines() {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        let reference = bases(f[0]);
        let start: usize = f[1].parse().unwrap();
        let end: usize = f[2].parse().unwrap();
        let expected = f[4];
        let raw = Variant {
            pos: Interbase::new(start),
            del: reference[start..end].to_vec(),
            ins: bases(f[3]),
        };
        match to_hgvs(&reference, &raw) {
            Ok(got) => {
                checked += 1;
                if got == expected {
                    agree += 1;
                } else if mismatches.len() < 25 {
                    mismatches.push(format!(
                        "seq={} [{start},{end}) alt={:?}  cistron={got}  biocommons={expected}",
                        f[0], f[3]
                    ));
                }
            }
            Err(e) => {
                errors += 1;
                if mismatches.len() < 25 {
                    mismatches.push(format!(
                        "ERROR seq={} [{start},{end}) alt={:?}  cistron={e:?}  biocommons={expected}",
                        f[0], f[3]
                    ));
                }
            }
        }
    }

    eprintln!(
        "checked {checked}, agree {agree}, mismatch {}, cistron-errors {errors}",
        checked - agree
    );
    for m in &mismatches {
        eprintln!("  {m}");
    }
    assert_eq!(
        agree,
        checked,
        "cistron-hgvs disagrees with biocommons on {} cases",
        checked - agree
    );
    assert_eq!(
        errors, 0,
        "cistron-hgvs failed to render {errors} variants biocommons can"
    );
    assert!(checked > 1000, "corpus too small: {checked}");
}
