//! VRS conformance: `cistron`'s GA4GH identifiers must match the ga4gh.vrs
//! reference implementation byte-for-byte. The corpus in `vrs_vectors.tsv` was
//! generated by vrs-python (see `scripts/gen_vrs_vectors.py`) and committed, so
//! this runs on every `cargo test` with no Python dependency.

use cistron_identity::vrs::allele_id;

#[test]
fn matches_the_vrs_python_reference_corpus() {
    let corpus = include_str!("vrs_vectors.tsv");
    let mut checked = 0usize;

    for (lineno, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(f.len(), 5, "malformed corpus line {}", lineno + 1);
        let (acc, alt, expected) = (f[0], f[3], f[4]);
        let start: u64 = f[1].parse().expect("start");
        let end: u64 = f[2].parse().expect("end");

        assert_eq!(
            allele_id(acc, start, end, alt),
            expected,
            "VRS id mismatch on line {}: {acc} [{start},{end}) alt={alt:?}",
            lineno + 1
        );
        checked += 1;
    }

    eprintln!("validated {checked} VRS ids against the vrs-python reference corpus");
    assert!(checked > 1000, "corpus too small: {checked}");
}
