//! VRS normalization + state differential: `cistron_identity::ga4gh_allele_id`
//! (fully-justified normalization, then the literal-vs-run-length state choice)
//! must match vrs-python's `normalize` + `ga4gh_identify` byte-for-byte. The
//! corpus in `vrs_norm_vectors.tsv` was generated by the reference
//! implementation (see `scripts/gen_vrs_norm_vectors.py`) over random sequences
//! and variants — literal *and* RLE cases — and committed, so this runs on every
//! `cargo test` with no Python dependency.

use cistron::{Base, Interbase, Variant};
use cistron_identity::ga4gh_allele_id;

const ACC: &str = "SQ.IIB53T8CNeJJdUqzn9V_JnRtQadwWCbl";

fn bases(s: &str) -> Vec<Base> {
    s.chars()
        .map(|c| match c {
            'A' => Base::A,
            'C' => Base::C,
            'G' => Base::G,
            'T' => Base::T,
            other => panic!("bad base {other}"),
        })
        .collect()
}

#[test]
fn ga4gh_allele_id_matches_vrs_python() {
    let corpus = include_str!("vrs_norm_vectors.tsv");
    let mut checked = 0usize;

    for (lineno, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(f.len(), 5, "malformed corpus line {}", lineno + 1);
        let reference = bases(f[0]);
        let start: usize = f[1].parse().unwrap();
        let end: usize = f[2].parse().unwrap();
        let expected = f[4];

        // The raw variant exactly as fed to vrs-python.
        let raw = Variant {
            pos: Interbase::new(start),
            del: reference[start..end].to_vec(),
            ins: bases(f[3]),
        };

        let id = ga4gh_allele_id(ACC, &reference, &raw).expect("well-formed input");
        assert_eq!(
            id,
            expected,
            "VRS id mismatch on line {}: seq={} [{start},{end}) alt={:?}",
            lineno + 1,
            f[0],
            f[3]
        );
        checked += 1;
    }

    eprintln!("validated {checked} VRS allele ids (literal + RLE) against vrs-python");
    assert!(checked > 1000, "corpus too small: {checked}");
}
